name = terras_capixabas
title = Terras Capixabas
description = Uma enorme e ambiciosa simulação contínua, que vem com um mundo chamado Vila Capixaba, com centenas de decorações funcionais e modelos de todos os tipos, inspirados no Leste do Brasil!
depends = default, mobs
author = Aloan Moreira - aloan.1@hotmail.com - aloan.neocities.org
min_minetest_version = 5.0
